PLAN_ORDER = ["free", "starter", "pro", "max", "scale", "enterprise"]


def _with_compat_aliases(plan_id: str, data: dict) -> dict:
    plan = dict(data)
    plan["features"] = [
        feature
        for feature in plan.get("features", [])
        if "zapier" not in str(feature).lower()
    ]
    plan["id"] = plan_id
    plan["monthly_tickets"] = plan["tickets_per_month"]
    plan["overage_price"] = plan["overage_rate"]
    plan["price"] = plan["monthly_price"] or 0
    feature_flags = dict(plan.get("feature_flags", {}))
    feature_flags.pop("zapier", None)
    plan["feature_flags"] = feature_flags
    plan["razorpay_plan_ids"] = {
        "monthly": f"synapflow_{plan_id}_monthly",
        "annual": f"synapflow_{plan_id}_annual",
    } if plan_id in {"starter", "pro", "max", "scale"} else {}
    return plan


PLANS = {
    "free": _with_compat_aliases(
        "free",
        {
            "name": "Free",
            "monthly_price": 0,
            "annual_price": 0,
            "annual_savings": 0,
            "tickets_per_month": 50,
            "team_seats": 1,
            "overage_rate": 0,
            "trial_days": None,
            "trial_requires_card": False,
            "features": [
                "AI Complaint Classification",
                "Basic Analytics Dashboard",
                "Email Ingestion",
                "Customer Complaint History (Basic)",
                "Email Support",
                "50 Tickets / Month",
                "1 Team Seat",
            ],
            "feature_flags": {
                "ai_classification": True,
                "ai_auto_reply": False,
                "sentiment_analysis": False,
                "pattern_detection": False,
                "churn_risk_scoring": False,
                "analytics_level": "basic",
                "sla_tracking": False,
                "api_access": False,
                "custom_branding": False,
                "root_cause_analysis": False,
                "team_performance": False,
                "audit_log": False,
                "ai_suggested_responses": False,
                "ticketing_state_machine": True,
                "sla_management": False,
                "customer_360": False,
                "auto_reply_approval_queue": True,
                "rbi_compliance": False,
                "auto_escalation": False,
                "multi_channel": ["email"],
                "integrations_count": 1,
                "webhooks": False,
            },
        },
    ),
    "starter": _with_compat_aliases(
        "starter",
        {
            "name": "Starter",
            "monthly_price": 2999,
            "annual_price": 29990,
            "annual_savings": 5998,
            "tickets_per_month": 500,
            "team_seats": 3,
            "overage_rate": 4,
            "trial_days": 30,
            "trial_requires_card": False,
            "features": [
                "AI Complaint Classification",
                "Basic Analytics Dashboard",
                "Email Ingestion",
                "Customer Complaint History (Basic)",
                "Email Support",
                "1 Integration (Email)",
            ],
            "feature_flags": {
                "ai_classification": True,
                "ai_auto_reply": False,
                "sentiment_analysis": False,
                "pattern_detection": False,
                "churn_risk_scoring": False,
                "analytics_level": "basic",
                "sla_tracking": False,
                "api_access": False,
                "custom_branding": False,
                "root_cause_analysis": False,
                "team_performance": False,
                "audit_log": False,
                "ai_suggested_responses": False,
                "ticketing_state_machine": True,
                "sla_management": False,
                "customer_360": False,
                "auto_reply_approval_queue": True,
                "rbi_compliance": False,
                "auto_escalation": False,
                "multi_channel": ["email"],
                "integrations_count": 1,
                "webhooks": False,
            },
        },
    ),
    "pro": _with_compat_aliases(
        "pro",
        {
            "name": "Pro",
            "monthly_price": 4999,
            "annual_price": 49990,
            "annual_savings": 9998,
            "tickets_per_month": 2000,
            "team_seats": 10,
            "overage_rate": 3,
            "trial_days": 14,
            "trial_requires_card": True,
            "features": [
                "Everything in Starter",
                "Sentiment Analysis",
                "Complaint Pattern Detection",
                "SLA Tracking + Alerts",
                "AI-Suggested Responses",
                "WhatsApp Ingestion",
                "Website Ingestion",
                "Advanced Analytics",
                "Resolution Time Reports",
                "Full Customer History + Sentiment Timeline",
                "3 Integrations (Email, WhatsApp, Website)",
            ],
            "feature_flags": {
                "ai_classification": True,
                "ai_auto_reply": False,
                "sentiment_analysis": True,
                "pattern_detection": True,
                "churn_risk_scoring": False,
                "analytics_level": "advanced",
                "sla_tracking": True,
                "api_access": False,
                "custom_branding": False,
                "root_cause_analysis": False,
                "team_performance": False,
                "audit_log": False,
                "ai_suggested_responses": True,
                "ticketing_state_machine": True,
                "sla_management": True,
                "customer_360": True,
                "auto_reply_approval_queue": True,
                "rbi_compliance": False,
                "auto_escalation": False,
                "multi_channel": ["email", "whatsapp", "website"],
                "integrations_count": 3,
                "webhooks": False,
            },
        },
    ),
    "max": _with_compat_aliases(
        "max",
        {
            "name": "Max",
            "monthly_price": 9999,
            "annual_price": 99990,
            "annual_savings": 19998,
            "tickets_per_month": 10000,
            "team_seats": 25,
            "overage_rate": 2,
            "trial_days": 14,
            "trial_requires_card": True,
            "features": [
                "Everything in Pro",
                "AI Auto-Reply",
                "Churn Risk Scoring",
                "Root Cause Analysis Reports (Weekly + Monthly)",
                "Team Performance Dashboard",
                "Audit Log + Compliance Export",
                "API Access",
                "Website Ingestion",
                "Instagram + Google Reviews Ingestion",
                "5 Integrations (Email, WhatsApp, Website, Instagram, Google Reviews)",
                "Priority Support",
            ],
            "feature_flags": {
                "ai_classification": True,
                "ai_auto_reply": True,
                "sentiment_analysis": True,
                "pattern_detection": True,
                "churn_risk_scoring": True,
                "analytics_level": "advanced",
                "sla_tracking": True,
                "api_access": True,
                "custom_branding": False,
                "root_cause_analysis": True,
                "team_performance": True,
                "audit_log": True,
                "ai_suggested_responses": True,
                "ticketing_state_machine": True,
                "sla_management": True,
                "customer_360": True,
                "auto_reply_approval_queue": True,
                "rbi_compliance": False,
                "auto_escalation": False,
                "multi_channel": ["email", "whatsapp", "website", "instagram", "google_reviews"],
                "integrations_count": 5,
                "webhooks": False,
            },
        },
    ),
    "scale": _with_compat_aliases(
        "scale",
        {
            "name": "Scale",
            "monthly_price": 99999,
            "annual_price": 999990,
            "annual_savings": 199998,
            "tickets_per_month": 100000,
            "team_seats": 100,
            "overage_rate": 1,
            "trial_days": 14,
            "trial_requires_card": True,
            "features": [
                "Everything in Max",
                "RBI Compliance (Eligible Institutions)",
                "Custom Branding",
                "Webhook Access",
                "Custom Channel Ingestion",
                "Website Ingestion",
                "6 Integrations (Email, WhatsApp, Website, Instagram, Google Reviews, Custom)",
                "1,00,000 tickets/month",
                "100 team seats",
                "Dedicated CSM",
            ],
            "feature_flags": {
                "ai_classification": True,
                "ai_auto_reply": True,
                "sentiment_analysis": True,
                "pattern_detection": True,
                "churn_risk_scoring": True,
                "analytics_level": "full",
                "sla_tracking": True,
                "api_access": True,
                "custom_branding": True,
                "root_cause_analysis": True,
                "team_performance": True,
                "audit_log": True,
                "ai_suggested_responses": True,
                "ticketing_state_machine": True,
                "sla_management": True,
                "customer_360": True,
                "auto_reply_approval_queue": True,
                "rbi_compliance": True,
                "auto_escalation": False,
                "multi_channel": ["email", "whatsapp", "website", "instagram", "google_reviews", "custom"],
                "integrations_count": 6,
                "webhooks": True,
            },
        },
    ),
    "enterprise": _with_compat_aliases(
        "enterprise",
        {
            "name": "Enterprise",
            "monthly_price": None,
            "annual_price": None,
            "annual_savings": None,
            "tickets_per_month": 999999,
            "team_seats": 999,
            "overage_rate": 0,
            "trial_days": None,
            "trial_requires_card": False,
            "features": [
                "Everything in Scale",
                "RBI Compliance (Eligible Institutions)",
                "White-glove Onboarding",
                "Custom AI Model Training",
                "SLA Guarantees in Contract",
                "Custom Integrations",
                "Dedicated Infrastructure",
                "Manual Invoicing",
                "Unlimited Everything",
            ],
            "feature_flags": {
                "ai_classification": True,
                "ai_auto_reply": True,
                "sentiment_analysis": True,
                "pattern_detection": True,
                "churn_risk_scoring": True,
                "analytics_level": "custom",
                "sla_tracking": True,
                "api_access": True,
                "custom_branding": True,
                "root_cause_analysis": True,
                "team_performance": True,
                "audit_log": True,
                "ai_suggested_responses": True,
                "ticketing_state_machine": True,
                "sla_management": True,
                "customer_360": True,
                "auto_reply_approval_queue": True,
                "rbi_compliance": True,
                "auto_escalation": True,
                "multi_channel": ["all"],
                "integrations_count": 999,
                "webhooks": True,
            },
        },
    ),
}

# Sanity checks to prevent missing premium paths at startup
EXPECTED_PLANS = ["free", "starter", "pro", "max", "scale", "enterprise"]
for expected in EXPECTED_PLANS:
    if expected not in PLANS:
        raise AssertionError(f"Missing expected plan configuration: {expected}")

scale_plan = PLANS.get("scale")
if not scale_plan:
    raise AssertionError("Scale plan is not configured")

if scale_plan.get("monthly_price") is None or scale_plan.get("annual_price") is None:
    raise AssertionError("Scale plan must include monthly_price and annual_price")

if not scale_plan.get("razorpay_plan_ids") or "monthly" not in scale_plan.get("razorpay_plan_ids", {}):
    raise AssertionError("Scale plan must include razorpay_plan_ids for monthly and annual")
