export const metadata = {
  title: 'Privacy Policy — SynapFlow',
}

export default function PrivacyPolicyPage() {
  return (
    <article className="prose prose-slate max-w-none">
      <h1>Privacy Policy</h1>
      <p className="text-slate-500 text-sm">
        Version 1.0 · Effective date: June 1, 2026 · Last reviewed: June 1, 2026
      </p>
      <p>
        This Privacy Policy explains how SynapTec Pvt. Ltd. ("SynapFlow", "we", "our", or "us") collects, uses,
        stores, and protects personal data in connection with the SynapFlow platform. It applies to all users
        of our website and services.
      </p>
      <p>
        We comply with the <strong>Digital Personal Data Protection (DPDP) Act, 2023</strong>, the{' '}
        <strong>IT Act, 2000 and SPDI Rules, 2011</strong>, the{' '}
        <strong>EU General Data Protection Regulation (GDPR)</strong>, the{' '}
        <strong>California Consumer Privacy Act (CCPA/CPRA)</strong>, and applicable RBI guidelines.
      </p>

      {/* 1. Identity & Contact */}
      <h2>1. Identity &amp; Contact</h2>
      <p><strong>Data Controller / Fiduciary:</strong> SynapTec Pvt. Ltd.</p>
      <p><strong>Registered Address:</strong> [INSERT REGISTERED INDIAN ADDRESS]</p>
      <p><strong>Privacy contact:</strong> <a href="mailto:privacy@synapflow.in">privacy@synapflow.in</a></p>
      <p><strong>Data Protection Officer (DPO):</strong> [INSERT DPO NAME] · <a href="mailto:dpo@synapflow.in">dpo@synapflow.in</a></p>
      <p><strong>Grievance Officer:</strong> See <a href="#grievance">Section 10</a> below.</p>

      {/* 2. Data We Collect */}
      <h2>2. Personal Data We Collect</h2>
      <p>We collect personal data in two capacities:</p>
      <h3>2A. Data Principals / End Users</h3>
      <p>These are the customers of our clients whose complaints are processed through SynapFlow.</p>
      <ul>
        <li><strong>Identity data:</strong> name, email address, phone number</li>
        <li><strong>Complaint content:</strong> free-text complaints and attachments — this is <em>Sensitive Personal Data</em> under IT (SPDI) Rules, 2011</li>
        <li><strong>AI-inferred data:</strong> sentiment scores, urgency scores, churn risk scores, complaint categories generated by our AI</li>
        <li><strong>Communication metadata:</strong> WhatsApp message metadata, Gmail message identifiers</li>
      </ul>
      <h3>2B. Business Users / Operators</h3>
      <p>These are the agents, supervisors, and administrators who log in to the SynapFlow platform.</p>
      <ul>
        <li><strong>Identity data:</strong> name, work email address</li>
        <li><strong>Financial data:</strong> payment method, billing address, transaction history (via Razorpay)</li>
        <li><strong>Behavioural / Usage data:</strong> login timestamps, feature usage, IP addresses, session identifiers</li>
      </ul>

      {/* 3. Legal Basis */}
      <h2>3. Legal Basis for Processing</h2>
      <table>
        <thead>
          <tr><th>Data category</th><th>Legal basis (GDPR)</th><th>Legal basis (DPDP)</th></tr>
        </thead>
        <tbody>
          <tr><td>Business User account data</td><td>Contractual necessity (Art. 6(1)(b))</td><td>Consent / contractual necessity (§4)</td></tr>
          <tr><td>End-user complaint content</td><td>Legitimate interest of client (Art. 6(1)(f))</td><td>Client's consent from data principal (§6)</td></tr>
          <tr><td>Payment &amp; billing data</td><td>Contractual necessity (Art. 6(1)(b))</td><td>Contractual necessity (§4)</td></tr>
          <tr><td>AI-inferred scores</td><td>Legitimate interest (Art. 6(1)(f))</td><td>Permitted processing under client's instruction (§4)</td></tr>
          <tr><td>Audit / security logs</td><td>Legal obligation (Art. 6(1)(c))</td><td>Legal obligation — DPDP Rules 2025 §8</td></tr>
          <tr><td>RBI MIS reports</td><td>Legal obligation (Art. 6(1)(c))</td><td>Legal obligation — RBI directives (§4)</td></tr>
        </tbody>
      </table>

      {/* 4. Purpose Limitation */}
      <h2>4. Purpose Limitation</h2>
      <p>Personal data is collected and processed only for the following purposes:</p>
      <ol>
        <li>Providing complaint management, routing, analytics, and AI-assisted reply services</li>
        <li>AI-driven classification, sentiment analysis, urgency scoring, and reply drafting</li>
        <li>Regulatory compliance reporting (RBI TAT/MIS reports for eligible clients)</li>
        <li>Billing and subscription management via Razorpay</li>
        <li>Platform security, fraud prevention, and immutable audit logging</li>
        <li>Service improvement using <em>anonymised and aggregated</em> data only</li>
      </ol>
      <p>
        <strong>Data is not used for:</strong> selling to third parties, advertising, or profiling for purposes
        unrelated to complaint management.
      </p>

      {/* 5. Data Retention */}
      <h2>5. Data Retention</h2>
      <table>
        <thead>
          <tr><th>Data category</th><th>Retention period</th><th>Reason</th></tr>
        </thead>
        <tbody>
          <tr><td>Complaint tickets &amp; content</td><td>Duration of client contract + 3 years</td><td>Regulatory audit requirements</td></tr>
          <tr><td>AI interaction logs</td><td>1 year minimum</td><td>DPDP Rules 2025, §8</td></tr>
          <tr><td>Access / traffic logs</td><td>1 year minimum</td><td>DPDP Rules 2025</td></tr>
          <tr><td>Payment transaction data</td><td>8 years</td><td>Indian tax / GST law</td></tr>
          <tr><td>Business User account data</td><td>Duration of subscription + 1 year</td><td>Contractual</td></tr>
          <tr><td>Deleted / churned account data</td><td>30 days post-deletion, then permanently purged</td><td>DPDP §8(7)</td></tr>
        </tbody>
      </table>

      {/* 6. Data Sharing */}
      <h2>6. Data Sharing &amp; Sub-processors</h2>
      <p>We share personal data only with the following sub-processors:</p>
      <table>
        <thead>
          <tr><th>Sub-processor</th><th>Purpose</th><th>Location</th><th>Safeguard</th></tr>
        </thead>
        <tbody>
          <tr><td>Google (Gemini AI API)</td><td>AI classification &amp; text generation</td><td>US / Global</td><td>Standard Contractual Clauses (SCCs); data is pseudonymised before transmission</td></tr>
          <tr><td>Supabase (PostgreSQL)</td><td>Database hosting</td><td>India (ap-south-1, Mumbai)</td><td>DPA in place; AES-256 encryption at rest</td></tr>
          <tr><td>Razorpay</td><td>Payment processing</td><td>India</td><td>PCI-DSS compliant; RBI-regulated entity</td></tr>
          <tr><td>Google (Gmail API)</td><td>Email inbox ingestion</td><td>US / Global</td><td>OAuth 2.0; minimal scope (gmail.readonly only)</td></tr>
          <tr><td>Meta (WhatsApp Business API)</td><td>Complaint ingestion via WhatsApp</td><td>US / Global</td><td>Meta DPA; SCCs</td></tr>
          <tr><td>Railway (hosting)</td><td>Application hosting &amp; deployment</td><td>Asia-Pacific</td><td>SOC 2 compliant; encrypted in transit (TLS 1.2+)</td></tr>
        </tbody>
      </table>
      <p><strong>We do not sell personal data to third parties.</strong></p>

      {/* 7. Data Localization */}
      <h2>7. Data Localization</h2>
      <p>
        SynapFlow's primary database is hosted on Supabase in the <strong>ap-south-1 (Mumbai, India)</strong> region
        in compliance with the RBI Data Localization Directive (April 2018, updated May 2025).
      </p>
      <p>
        Payment-related data processed via Razorpay is stored exclusively on servers in India per RBI mandate.
      </p>
      <p>
        For AI processing via the Gemini API: complaint content is pseudonymised (PII tokens are replaced)
        before transmission to Google's servers, and results are detokenised on return. Raw PII is not
        permanently stored outside India.
      </p>

      {/* 8. Your Rights */}
      <h2>8. Your Rights</h2>
      <h3>Under Indian Law (DPDP Act 2023)</h3>
      <ul>
        <li><strong>Right to access:</strong> Obtain a summary of personal data processed and the processing activities.</li>
        <li><strong>Right to correction and erasure:</strong> Correct inaccurate data or request erasure when the purpose is fulfilled.</li>
        <li><strong>Right to grievance redressal:</strong> Raise a complaint with our Grievance Officer; acknowledged within 48 hours.</li>
        <li><strong>Right to nominate:</strong> Nominate another person to exercise your rights in case of death or incapacity.</li>
        <li><strong>Right to withdraw consent:</strong> At any time; withdrawal does not affect prior lawful processing.</li>
      </ul>
      <h3>Under EU Law (GDPR)</h3>
      <ul>
        <li>Right to access (Art. 15)</li>
        <li>Right to rectification (Art. 16)</li>
        <li>Right to erasure / "right to be forgotten" (Art. 17)</li>
        <li>Right to restriction of processing (Art. 18)</li>
        <li>Right to data portability in machine-readable format — JSON or CSV (Art. 20)</li>
        <li>Right to object to automated decision-making, including AI sentiment and churn scoring (Art. 21 &amp; 22)</li>
        <li>Right to lodge a complaint with your EU supervisory authority</li>
      </ul>
      <h3>Under US Law (CCPA / CPRA)</h3>
      <ul>
        <li>Right to know what personal information is collected and how it is used</li>
        <li>Right to delete personal information</li>
        <li>Right to correct inaccurate personal information</li>
        <li>Right to opt out of sale or sharing of personal information — <strong>SynapFlow does not sell personal data</strong></li>
        <li>Right to limit use of sensitive personal information</li>
      </ul>
      <p>
        <strong>How to exercise your rights:</strong> Email <a href="mailto:dpo@synapflow.in">dpo@synapflow.in</a>.
        Response times: Indian requests — acknowledged within 48 hours, resolved within 30 days;
        GDPR requests — 30 days; CCPA requests — 45 days.
      </p>

      {/* 9. AI & Automated Processing */}
      <h2>9. Automated Decision-Making &amp; AI Transparency</h2>
      <p>
        SynapFlow uses Google Gemini AI to automatically classify complaints, score sentiment (1–5 scale),
        assign urgency, generate draft replies, and predict churn risk.
      </p>
      <p>
        <strong>All AI-generated reply drafts are subject to human review before being sent</strong> (Human-in-the-Loop).
        Automated scoring does not constitute a final binding decision; human agents make final determinations.
      </p>
      <p>
        You have the right to request human review of any AI-generated outcome. AI-generated content is
        clearly labelled as "AI Draft — Pending Review" in the operator interface.
      </p>

      {/* 10. Grievance Officer */}
      <h2 id="grievance">10. Grievance Officer</h2>
      <p>
        As required by IT (SPDI) Rules 2011, Rule 5(9) and DPDP Act §13:
      </p>
      <table>
        <tbody>
          <tr><td><strong>Name</strong></td><td>[INSERT GRIEVANCE OFFICER NAME]</td></tr>
          <tr><td><strong>Designation</strong></td><td>Data Protection Officer / Grievance Officer</td></tr>
          <tr><td><strong>Organisation</strong></td><td>SynapTec Pvt. Ltd.</td></tr>
          <tr><td><strong>Address</strong></td><td>[INSERT REGISTERED INDIAN ADDRESS]</td></tr>
          <tr><td><strong>Email</strong></td><td><a href="mailto:grievance@synapflow.in">grievance@synapflow.in</a></td></tr>
          <tr><td><strong>Phone</strong></td><td>[INSERT INDIAN PHONE NUMBER]</td></tr>
          <tr><td><strong>Availability</strong></td><td>Monday–Friday, 9 AM–6 PM IST</td></tr>
          <tr><td><strong>Response time</strong></td><td>Acknowledged within 48 hours; resolved within 30 days</td></tr>
        </tbody>
      </table>

      {/* 11. Breach Notification */}
      <h2>11. Data Breach Notification</h2>
      <p>In the event of a personal data breach, SynapFlow will:</p>
      <ul>
        <li>Notify the Data Protection Board of India within 72 hours (once operational under DPDP)</li>
        <li>Notify affected EU supervisory authorities within 72 hours</li>
        <li>Notify affected Data Principals without undue delay with details of the breach, likely consequences, and mitigation steps</li>
        <li>Notify affected clients within 24 hours of discovery</li>
      </ul>

      {/* 12. Cookies */}
      <h2>12. Cookies</h2>
      <p>
        We use strictly necessary cookies (session authentication, CSRF protection) and optional analytics cookies.
        See our full <a href="/legal/cookie-policy">Cookie Policy</a> for details and preference controls.
      </p>

      {/* 13. Changes */}
      <h2>13. Changes to This Policy</h2>
      <p>
        We will provide at least 15 days' advance notice of material changes via email and in-app notification.
        Continued use of the platform after the notice period constitutes acceptance.
      </p>

      <p className="text-sm text-slate-500 mt-8 border-t pt-4">
        Questions? Email <a href="mailto:privacy@synapflow.in">privacy@synapflow.in</a> ·{' '}
        <em>⚠️ This policy has been prepared based on publicly available legal information. It should be reviewed by qualified Indian legal counsel before publication.</em>
      </p>
    </article>
  )
}
